import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { esES } from '@clerk/localizations';
import { Geist, Geist_Mono } from "next/font/google";
import "./style/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      localization={esES}
      {...(typeof window !== "undefined" && {
        navigate: (to: string) => window.history.pushState(null, "", to),
      })}
    >
      <html lang="es">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-end items-center p-4 gap-4 h-12 bg-white shadow-md">
            <div className="flex items-center gap-2">
              <SignedOut>
                <SignInButton mode="modal">
                  <button>Iniciar sesión</button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <button>Registrarse</button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton showName={true} />
              </SignedIn>
            </div>
          </header>

          {children}

          <footer className="flex justify-center items-center p-4 gap-4 h-12 bg-white shadow-md">
            <p className="text-sm text-gray-500">
              © 2099 . Todos los derechos reservados.
            </p>
            </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
